### PR TITLE
Set title / double action bug / pullRequest tests / lock issue

### LINKED ISSUE #15: Derek adds a label when labelling comment is deleted
Course of action to reproduce:

`Derek add label: fred` <-- label added
`Derek remove label: fred` <-- label removed
Delete comment 1 <-- label added again

Potential fix would be to inspect the POSTed JSON to see if `"action": "deleted"` is set and cause Derek to refuse to act within `AddLabel` and `RemoveLabel` in this instance.  Within the code this would be `req.Action`

### LINKED ISSUE #21: .DEREK.yml feature flags + maintainers list
The .DEREK.yml file should take over the place of the MAINTAINERS file.

This will support roles / actions and mapping users to roles, but initially will look like this:

```
maintainers:
 - alexellis
 - rgee0
features:
 - dco_check
 - comments
```

See 2.0 extensions - https://github.com/alexellis/derek/issues/22

### LINKED ISSUE #24: Proposal: Enable changing of issue/PR title
Add `Derek set title: This is the new title` functionality so that maintainers can painlessly manage imprecise or ambiguous issue titles.

### LINKED ISSUE #28: Proposal:  Derek should lock / unlock threads
Threads in PRs and Issues should be lockable by issuing `Derek lock` and unlock-able by issuing `Derek unlock`

### PR DESCRIPTION
**Pull request by rgee0**
Fixes #21 
Fixes #24 
Fixes #15 
Fixes #28

Summary of changes:

* Added `go test` to Dockerfile.
* Added a check that the issue_comment webhook action isn't `deleted` before taking action, as this was causing Derek to re-trigger when comments originally aimed at Derek deleted.
* Added a check that the pull_request webhook action isn't `closed` before taking action, as this was causing Derek to perform the dco_check unnecessarily.
* Added tests to cover some of the pullRequestHander methods.
* Implemented `Derek set title:`, `Derek lock` & `Derek unlock` commands
* Updated `README.md` to cover new features, marking the lock & title features as complete and adding two additional features.
* Extracted a method in the open/close switch clause to assess requested state against current state and return whether the requested transition is valid.  Added a test for this.
* Added checking to `setTitle`, `close`, `reopen`, `lock` & `unlock` so that API calls are only made when necessary hence minimizing the effect on API rate limits.
* Broadened the scope of the `Issue` type to enable capturing details required for evaluating whether requests to the API are necessary.

Currently deployed at [rgee0/Test](https://github.com/rgee0/Test) for evaluation.

n.b. The github comparison views  aren't displaying the changes at all well.  It doesn't seem to be lining the line numbers up correctly.

### CODE REVIEW

File: commentHandler.go [hunk 1]
```diff
@@ -130,24 +134,84 @@ func handleComment(req types.IssueCommentOuter) {
 	case "close", "reopen":
 		fmt.Printf("%s wants to %s issue #%d\n", req.Comment.User.Login, command.Type, req.Issue.Number)
 
+		newState, validAction := assessState(command.Type, req.Issue.State)
```
Comment (alexellis) [inline commentHandler.go]: Maybe call it `isValidAction` / `validTransition` ?

File: commentHandler.go [hunk 2]
```diff
@@ -130,24 +134,84 @@ func handleComment(req types.IssueCommentOuter) {
...
 			log.Fatalln(err)
 		}
-		fmt.Printf("Request to %s issue #%d by %s was successful.\n", command.Type, req.Issue.Number, req.Comment.User.Login)
+
+		fmt.Printf("Request to set the title of issue #%d by %s was successful.\n", req.Issue.Number, req.Comment.User.Login)
 
 		break
+
+	case "Lock":
+		fmt.Printf("%s wants to lock issue #%d\n", req.Comment.User.Login, req.Issue.Number)
```
Comment (alexellis) [inline commentHandler.go]: This code block is getting messy - are we at the point in this PR where we need new methods that optionally return `error` ?

File: commentHandler.go (hunk 1 above)
Comment (rgee0) [reply commentHandler.go]: Yes

File: commentHandler.go (hunk 2 above)
Comment (rgee0) [reply commentHandler.go]: This was in my thinking as we move to packages

**Comment by rgee0** [comment]
@alexellis I've changed `validAction` to be `validTransition`.

I've also repointed the rgee0 [bot] on [rgee0/Test](https://github.com/rgee0/Test) at an 'always on' endpoint for testing

**Comment by alexellis** [comment]
Thanks 👍

File: commentHandler.go (hunk 1 above)
Comment (alexellis) [reply commentHandler.go]: It still appears to be `assessState` in the commit comparison for me?

**Comment by alexellis** [comment]
Derek add label: enhancement

**Comment by alexellis** [comment]
Derek add label: enhancement

File: commentHandler.go (hunk 1 above)
Comment (rgee0) [reply commentHandler.go]: I think your original comment was referring to the variable.  If ‘it’ in the original comment was referencing the name of the function, rather than the variable, then the comment should be placed by the function definition, rather than by a particular use of the function.

Comment (alexellis) [reply commentHandler.go]: I want to change the name of the function too. I can see what you were going for with `assessState` but would like to pick something else.

**Comment by rgee0** [comment]
@alexellis `assessState` is now `checkTransition`.  also rebased to account for recent changes.

File: commentHandler.go (hunk 2 above)
Comment (alexellis) [reply commentHandler.go]: Can we break out into functions first please

File: commentHandler.go [hunk 3]
```diff
@@ -165,6 +229,9 @@ func parse(body string) *types.CommentAction {
 		"Derek unassign: ":     "Unassign",
 		"Derek close":          "close",
 		"Derek reopen":         "reopen",
+		"Derek set title: ":    "SetTitle",
```
Comment (alexellis) [inline commentHandler.go]: Also can we add: `edit title` please

File: commentHandler_test.go [hunk 4]
```diff
@@ -146,3 +146,99 @@ func Test_Parsing_Assignments(t *testing.T) {
...
+		},
+	}
+
+	for _, test := range stateOptions {
+		t.Run(test.title, func(t *testing.T) {
+
+			newState, validTransition := checkTransition(test.requestedAction, test.currentState)
+
+			if newState != test.expectedNewState || validTransition != test.expectedBool {
+				t.Errorf("\nStates - wanted: %s, got %s\nValidity - wanted: %t, got %t\n", test.expectedNewState, newState, test.expectedBool, validTransition)
```
Comment (alexellis) [inline commentHandler_test.go]: Good testing :100:
